// <auto-generated />
using System;
using CC_Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CC_Backend.Migrations
{
    [DbContext(typeof(NatureAIContext))]
    partial class NatureAIContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CC_Backend.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("CC_Backend.Models.Credentials", b =>
                {
                    b.Property<int>("CredentialsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CredentialsId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CredentialsId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Credentials");
                });

            modelBuilder.Entity("CC_Backend.Models.FriendList", b =>
                {
                    b.Property<int>("FriendListId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FriendListId"));

                    b.HasKey("FriendListId");

                    b.ToTable("FriendLists");
                });

            modelBuilder.Entity("CC_Backend.Models.Geodata", b =>
                {
                    b.Property<int>("GeodataId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GeodataId"));

                    b.Property<string>("Coordinates")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateWhenCollected")
                        .HasColumnType("datetime2");

                    b.Property<int>("StampCollectedId")
                        .HasColumnType("int");

                    b.HasKey("GeodataId");

                    b.HasIndex("StampCollectedId")
                        .IsUnique();

                    b.ToTable("GeoData");
                });

            modelBuilder.Entity("CC_Backend.Models.Icon", b =>
                {
                    b.Property<int>("IconId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IconId"));

                    b.Property<byte[]>("IconData")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("StampId")
                        .HasColumnType("int");

                    b.HasKey("IconId");

                    b.HasIndex("StampId")
                        .IsUnique();

                    b.ToTable("Icons");
                });

            modelBuilder.Entity("CC_Backend.Models.Stamp", b =>
                {
                    b.Property<int>("StampId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StampId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Facts")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rarity")
                        .HasColumnType("float");

                    b.HasKey("StampId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Stamps");
                });

            modelBuilder.Entity("CC_Backend.Models.StampCollected", b =>
                {
                    b.Property<int>("StampCollectedId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StampCollectedId"));

                    b.Property<int>("StampId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("StampCollectedId");

                    b.HasIndex("StampId");

                    b.HasIndex("UserId");

                    b.ToTable("StampsCollected");
                });

            modelBuilder.Entity("CC_Backend.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<int?>("FriendListId")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.HasIndex("FriendListId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CC_Backend.Models.Credentials", b =>
                {
                    b.HasOne("CC_Backend.Models.User", "User")
                        .WithOne("Credentials")
                        .HasForeignKey("CC_Backend.Models.Credentials", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CC_Backend.Models.Geodata", b =>
                {
                    b.HasOne("CC_Backend.Models.StampCollected", "StampCollected")
                        .WithOne("Geodata")
                        .HasForeignKey("CC_Backend.Models.Geodata", "StampCollectedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StampCollected");
                });

            modelBuilder.Entity("CC_Backend.Models.Icon", b =>
                {
                    b.HasOne("CC_Backend.Models.Stamp", "Stamp")
                        .WithOne("Icon")
                        .HasForeignKey("CC_Backend.Models.Icon", "StampId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stamp");
                });

            modelBuilder.Entity("CC_Backend.Models.Stamp", b =>
                {
                    b.HasOne("CC_Backend.Models.Category", "Category")
                        .WithMany("Stamps")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("CC_Backend.Models.StampCollected", b =>
                {
                    b.HasOne("CC_Backend.Models.Stamp", "Stamp")
                        .WithMany()
                        .HasForeignKey("StampId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CC_Backend.Models.User", "User")
                        .WithMany("StampsCollected")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stamp");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CC_Backend.Models.User", b =>
                {
                    b.HasOne("CC_Backend.Models.FriendList", "FriendList")
                        .WithMany("Users")
                        .HasForeignKey("FriendListId");

                    b.Navigation("FriendList");
                });

            modelBuilder.Entity("CC_Backend.Models.Category", b =>
                {
                    b.Navigation("Stamps");
                });

            modelBuilder.Entity("CC_Backend.Models.FriendList", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("CC_Backend.Models.Stamp", b =>
                {
                    b.Navigation("Icon")
                        .IsRequired();
                });

            modelBuilder.Entity("CC_Backend.Models.StampCollected", b =>
                {
                    b.Navigation("Geodata")
                        .IsRequired();
                });

            modelBuilder.Entity("CC_Backend.Models.User", b =>
                {
                    b.Navigation("Credentials")
                        .IsRequired();

                    b.Navigation("StampsCollected");
                });
#pragma warning restore 612, 618
        }
    }
}
